/**
 * server/simulation/synthetic-market/synthetic-players.ts
 *
 * 40 named synthetic players with archetypes for demo mode.
 * Values are fully deterministic (no external deps, no DB).
 */

export type Archetype =
  | "HYPERCARRY"
  | "TANK_ANCHOR"
  | "UTILITY_SUPPORT"
  | "ASSASSIN"
  | "VETERAN"
  | "WILDCARD"
  | "SPLITPUSHER"
  | "TEAMFIGHT_CARRY"
  | "SCALING_MAGE"
  | "ENGAGE_SUPPORT";

export type SyntheticPlayer = {
  id: string;
  displayName: string;
  summonerTag: string;
  role: "TOP" | "JUNGLE" | "MID" | "ADC" | "SUPPORT";
  region: string;
  archetype: Archetype;
  basePrice: number;
  volatility: number;
  winRate: number;
  leaguePoints: number;
  pviBase: number;
  momentum: number;
  biography: string;
  strengths: string[];
  weaknesses: string[];
};

export const SYNTHETIC_PLAYERS: SyntheticPlayer[] = [
  // TOP LANERS
  {
    id: "syn-001",
    displayName: "NovaSplit",
    summonerTag: "NovaSplit#NA1",
    role: "TOP",
    region: "NA1",
    archetype: "SPLITPUSHER",
    basePrice: 142.5,
    volatility: 0.035,
    winRate: 57.8,
    leaguePoints: 892,
    pviBase: 71,
    momentum: 0.0041,
    biography: "Silent assassin of the top lane. Masters every split-pushing champion in the pool.",
    strengths: ["1v1 duels", "side lane control", "champion pool depth"],
    weaknesses: ["teamfight participation", "macro timing windows"],
  },
  {
    id: "syn-002",
    displayName: "IronBehemoth",
    summonerTag: "IronBehemoth#NA1",
    role: "TOP",
    region: "NA1",
    archetype: "TANK_ANCHOR",
    basePrice: 98.2,
    volatility: 0.021,
    winRate: 53.1,
    leaguePoints: 612,
    pviBase: 58,
    momentum: -0.0012,
    biography: "Immovable front line, willing to sacrifice stats for win conditions.",
    strengths: ["teamfight initiation", "engage combos", "durability"],
    weaknesses: ["laning phase", "scaling champions", "split push"],
  },
  {
    id: "syn-003",
    displayName: "VoidEdge",
    summonerTag: "VoidEdge#NA1",
    role: "TOP",
    region: "NA1",
    archetype: "HYPERCARRY",
    basePrice: 187.0,
    volatility: 0.054,
    winRate: 61.4,
    leaguePoints: 1204,
    pviBase: 82,
    momentum: 0.0087,
    biography: "NA1's most feared carry top — makes juggernauts look fragile.",
    strengths: ["late game scaling", "1v9 potential", "clutch mechanics"],
    weaknesses: ["early game vulnerability", "team dependency"],
  },
  {
    id: "syn-004",
    displayName: "CrimsonWard",
    summonerTag: "CrimsonWard#NA1",
    role: "TOP",
    region: "NA1",
    archetype: "VETERAN",
    basePrice: 112.0,
    volatility: 0.018,
    winRate: 55.0,
    leaguePoints: 748,
    pviBase: 65,
    momentum: 0.0003,
    biography: "7-season veteran. Efficiency over flash, always in the right place.",
    strengths: ["game sense", "consistency", "macro decisions"],
    weaknesses: ["mechanical ceiling", "limited champion pool"],
  },

  // JUNGLERS
  {
    id: "syn-005",
    displayName: "GhostPath",
    summonerTag: "GhostPath#NA1",
    role: "JUNGLE",
    region: "NA1",
    archetype: "ASSASSIN",
    basePrice: 203.4,
    volatility: 0.062,
    winRate: 63.2,
    leaguePoints: 1450,
    pviBase: 88,
    momentum: 0.0121,
    biography: "Untraceable. By the time you see him on the minimap, he's already won.",
    strengths: ["early skirmishes", "snowball potential", "map pressure"],
    weaknesses: ["late game falloff", "objective trading without follow"],
  },
  {
    id: "syn-006",
    displayName: "ZephyrRun",
    summonerTag: "ZephyrRun#NA1",
    role: "JUNGLE",
    region: "NA1",
    archetype: "TEAMFIGHT_CARRY",
    basePrice: 165.7,
    volatility: 0.044,
    winRate: 58.9,
    leaguePoints: 983,
    pviBase: 77,
    momentum: 0.0055,
    biography: "Syncs with his laners like clockwork. Teamfights become theater.",
    strengths: ["team coordination", "dragon/baron control", "zone control"],
    weaknesses: ["solo carries", "falling behind early"],
  },
  {
    id: "syn-007",
    displayName: "DuskCrawler",
    summonerTag: "DuskCrawler#NA1",
    role: "JUNGLE",
    region: "NA1",
    archetype: "SCALING_MAGE",
    basePrice: 89.5,
    volatility: 0.039,
    winRate: 50.8,
    leaguePoints: 523,
    pviBase: 52,
    momentum: -0.0031,
    biography: "Unconventional jungle paths; opponents never know what he's planning.",
    strengths: ["counter-jungling", "vision control", "tempo plays"],
    weaknesses: ["predictability when losing", "limited meta flexibility"],
  },
  {
    id: "syn-008",
    displayName: "TempestRage",
    summonerTag: "TempestRage#NA1",
    role: "JUNGLE",
    region: "NA1",
    archetype: "WILDCARD",
    basePrice: 231.0,
    volatility: 0.075,
    winRate: 64.7,
    leaguePoints: 1678,
    pviBase: 91,
    momentum: 0.0155,
    biography: "NA1's streakiest player. When he's on, nobody can stop him.",
    strengths: ["burst damage", "high-risk plays", "solo carry games"],
    weaknesses: ["inconsistency", "tilt susceptibility", "farm dependence"],
  },
  {
    id: "syn-009",
    displayName: "SilentForge",
    summonerTag: "SilentForge#NA1",
    role: "JUNGLE",
    region: "NA1",
    archetype: "VETERAN",
    basePrice: 127.3,
    volatility: 0.022,
    winRate: 56.1,
    leaguePoints: 810,
    pviBase: 68,
    momentum: 0.0018,
    biography: "Methodical and patient. Always three objectives ahead in his mental game.",
    strengths: ["objective control", "information gathering", "mental fortitude"],
    weaknesses: ["aggressive meta champions", "early skirmish weakness"],
  },

  // MID LANERS
  {
    id: "syn-010",
    displayName: "ArcaneFlux",
    summonerTag: "ArcaneFlux#NA1",
    role: "MID",
    region: "NA1",
    archetype: "SCALING_MAGE",
    basePrice: 178.9,
    volatility: 0.048,
    winRate: 60.3,
    leaguePoints: 1102,
    pviBase: 80,
    momentum: 0.0072,
    biography: "Patient mage with a lethal power spike at 3 items. The game changes when he spikes.",
    strengths: ["teamfight damage", "wave management", "late-game dominance"],
    weaknesses: ["early laning", "assassin matchups", "hard CC vulnerability"],
  },
  {
    id: "syn-011",
    displayName: "BladeRoot",
    summonerTag: "BladeRoot#NA1",
    role: "MID",
    region: "NA1",
    archetype: "ASSASSIN",
    basePrice: 219.5,
    volatility: 0.068,
    winRate: 62.5,
    leaguePoints: 1389,
    pviBase: 85,
    momentum: 0.0108,
    biography: "One-shot king. Can delete any target before they blink.",
    strengths: ["roaming", "burst combos", "pick potential"],
    weaknesses: ["tanky comps", "safe laners", "extended fights"],
  },
  {
    id: "syn-012",
    displayName: "ChaosPrism",
    summonerTag: "ChaosPrism#NA1",
    role: "MID",
    region: "NA1",
    archetype: "WILDCARD",
    basePrice: 95.1,
    volatility: 0.058,
    winRate: 51.4,
    leaguePoints: 578,
    pviBase: 54,
    momentum: -0.0022,
    biography: "Brings chaos to every lane — including his own sometimes.",
    strengths: ["innovative builds", "catching opponents off-guard", "outplay potential"],
    weaknesses: ["execution consistency", "loss streaks", "tilts hard"],
  },
  {
    id: "syn-013",
    displayName: "EclipseOrb",
    summonerTag: "EclipseOrb#NA1",
    role: "MID",
    region: "NA1",
    archetype: "HYPERCARRY",
    basePrice: 248.0,
    volatility: 0.059,
    winRate: 65.8,
    leaguePoints: 1820,
    pviBase: 93,
    momentum: 0.0182,
    biography: "Best mid on the server right now. Unmatched mechanics + decision-making.",
    strengths: ["1v9 potential", "matchup versatility", "mechanical excellence"],
    weaknesses: ["high draft priority", "ban-worthy profile"],
  },
  {
    id: "syn-014",
    displayName: "FrostPulse",
    summonerTag: "FrostPulse#NA1",
    role: "MID",
    region: "NA1",
    archetype: "UTILITY_SUPPORT",
    basePrice: 134.6,
    volatility: 0.027,
    winRate: 57.2,
    leaguePoints: 874,
    pviBase: 72,
    momentum: 0.0039,
    biography: "Plays mid as an extension of support — everyone on his team wins lane.",
    strengths: ["roam timing", "vision setup", "team synergy"],
    weaknesses: ["solo carrying", "carry champion pool"],
  },
  {
    id: "syn-015",
    displayName: "GlacierMind",
    summonerTag: "GlacierMind#NA1",
    role: "MID",
    region: "NA1",
    archetype: "VETERAN",
    basePrice: 109.8,
    volatility: 0.019,
    winRate: 54.7,
    leaguePoints: 701,
    pviBase: 63,
    momentum: 0.0005,
    biography: "Calm under pressure. Always the last one tilting on the team.",
    strengths: ["mental game", "late-game decision-making", "consistent farming"],
    weaknesses: ["mechanical limits", "high-tempo metas"],
  },

  // ADCs
  {
    id: "syn-016",
    displayName: "HyperShot",
    summonerTag: "HyperShot#NA1",
    role: "ADC",
    region: "NA1",
    archetype: "HYPERCARRY",
    basePrice: 195.4,
    volatility: 0.051,
    winRate: 61.9,
    leaguePoints: 1241,
    pviBase: 84,
    momentum: 0.0093,
    biography: "Carries a crosshair tattooed on his muscle memory. Never misses in teamfights.",
    strengths: ["teamfight positioning", "kiting mechanics", "high DPS output"],
    weaknesses: ["early laning alone", "support dependency"],
  },
  {
    id: "syn-017",
    displayName: "InkStrike",
    summonerTag: "InkStrike#NA1",
    role: "ADC",
    region: "NA1",
    archetype: "ASSASSIN",
    basePrice: 173.2,
    volatility: 0.063,
    winRate: 59.4,
    leaguePoints: 1022,
    pviBase: 78,
    momentum: 0.0067,
    biography: "Plays engage ADCs — gets in your face before you realize he's in range.",
    strengths: ["aggressive laning", "skirmishing", "unusual pick power"],
    weaknesses: ["fragility in extended fights", "high skill floor"],
  },
  {
    id: "syn-018",
    displayName: "JoltCarry",
    summonerTag: "JoltCarry#NA1",
    role: "ADC",
    region: "NA1",
    archetype: "SCALING_MAGE",
    basePrice: 88.7,
    volatility: 0.033,
    winRate: 51.0,
    leaguePoints: 504,
    pviBase: 51,
    momentum: -0.0044,
    biography: "All about the late-game spike. Early lane is his weakness, but mid-game he's unstoppable.",
    strengths: ["late-game damage ceiling", "scaling pick strength", "itemization depth"],
    weaknesses: ["early poke lanes", "weak early-mid skirmishes"],
  },
  {
    id: "syn-019",
    displayName: "KineticAim",
    summonerTag: "KineticAim#NA1",
    role: "ADC",
    region: "NA1",
    archetype: "VETERAN",
    basePrice: 143.7,
    volatility: 0.025,
    winRate: 56.6,
    leaguePoints: 883,
    pviBase: 70,
    momentum: 0.0027,
    biography: "Steady eddy of the ADC pool. Plays 5 meta ADCs at Challenger-level.",
    strengths: ["versatile champion pool", "laning consistency", "game reading"],
    weaknesses: ["not a 1v9 option", "needs team coordination"],
  },
  {
    id: "syn-020",
    displayName: "LightningReel",
    summonerTag: "LightningReel#NA1",
    role: "ADC",
    region: "NA1",
    archetype: "WILDCARD",
    basePrice: 261.8,
    volatility: 0.082,
    winRate: 66.1,
    leaguePoints: 1980,
    pviBase: 95,
    momentum: 0.0201,
    biography: "Server-best ADC when he's on form. Hottest asset in the market.",
    strengths: ["godlike teamfight mechanics", "top-5 NA1 player", "market darling"],
    weaknesses: ["inconsistency between series", "prone to off-day tilt"],
  },

  // SUPPORTS
  {
    id: "syn-021",
    displayName: "MoonShield",
    summonerTag: "MoonShield#NA1",
    role: "SUPPORT",
    region: "NA1",
    archetype: "UTILITY_SUPPORT",
    basePrice: 118.3,
    volatility: 0.023,
    winRate: 57.9,
    leaguePoints: 895,
    pviBase: 73,
    momentum: 0.0045,
    biography: "Peel-master. His ADCs never die in 2v2s. A must-have on any team.",
    strengths: ["peeling for carries", "vision control", "wave management"],
    weaknesses: ["solo carry potential", "low damage profile"],
  },
  {
    id: "syn-022",
    displayName: "NullPoint",
    summonerTag: "NullPoint#NA1",
    role: "SUPPORT",
    region: "NA1",
    archetype: "ENGAGE_SUPPORT",
    basePrice: 156.1,
    volatility: 0.042,
    winRate: 60.0,
    leaguePoints: 1105,
    pviBase: 79,
    momentum: 0.0078,
    biography: "Initiates teamfights from impossible angles. Always finds the backline.",
    strengths: ["engage range", "hook accuracy", "dive coordination"],
    weaknesses: ["peel matchups", "passive laning strategies"],
  },
  {
    id: "syn-023",
    displayName: "OracleVeil",
    summonerTag: "OracleVeil#NA1",
    role: "SUPPORT",
    region: "NA1",
    archetype: "UTILITY_SUPPORT",
    basePrice: 82.4,
    volatility: 0.017,
    winRate: 52.5,
    leaguePoints: 588,
    pviBase: 57,
    momentum: -0.0008,
    biography: "Highest ward placement on the server. Wins games through pure vision.",
    strengths: ["vision game", "objective setup", "split-second wards"],
    weaknesses: ["playmaking", "inconsistent laning phase"],
  },
  {
    id: "syn-024",
    displayName: "PrismaticCoil",
    summonerTag: "PrismaticCoil#NA1",
    role: "SUPPORT",
    region: "NA1",
    archetype: "ENGAGE_SUPPORT",
    basePrice: 188.5,
    volatility: 0.056,
    winRate: 62.0,
    leaguePoints: 1355,
    pviBase: 86,
    momentum: 0.0099,
    biography: "Terrifying engage support with perfect flash-combo precision.",
    strengths: ["playmaking", "teleport-engage synergy", "roam timing"],
    weaknesses: ["passive meta shifts", "limited peel"],
  },
  {
    id: "syn-025",
    displayName: "QuietThorn",
    summonerTag: "QuietThorn#NA1",
    role: "SUPPORT",
    region: "NA1",
    archetype: "VETERAN",
    basePrice: 103.6,
    volatility: 0.016,
    winRate: 54.3,
    leaguePoints: 679,
    pviBase: 62,
    momentum: 0.0001,
    biography: "Legendary support career spanning 8 seasons. Understands the game at a different level.",
    strengths: ["game knowledge", "consistent performance", "leadership"],
    weaknesses: ["mechanical decline", "fast-paced playstyle"],
  },

  // SECOND WAVE — Additional depth players
  {
    id: "syn-026",
    displayName: "RiftBreaker",
    summonerTag: "RiftBreaker#NA1",
    role: "TOP",
    region: "NA1",
    archetype: "TEAMFIGHT_CARRY",
    basePrice: 149.9,
    volatility: 0.038,
    winRate: 58.5,
    leaguePoints: 934,
    pviBase: 74,
    momentum: 0.0049,
    biography: "Turns every teamfight into a highlight reel. Plays for the crowd.",
    strengths: ["teamfight damage", "combos", "flashy mechanics"],
    weaknesses: ["methodical styles", "kiting compositions"],
  },
  {
    id: "syn-027",
    displayName: "StarForge",
    summonerTag: "StarForge#NA1",
    role: "JUNGLE",
    region: "NA1",
    archetype: "ENGAGE_SUPPORT",
    basePrice: 121.7,
    volatility: 0.031,
    winRate: 55.8,
    leaguePoints: 798,
    pviBase: 67,
    momentum: 0.0033,
    biography: "Bring-the-team jungler. Every camp cleared is an opportunity for his laners.",
    strengths: ["team-oriented", "dragon soul setups", "counter-engage"],
    weaknesses: ["solo carrying", "high carry metas"],
  },
  {
    id: "syn-028",
    displayName: "TwilightEdge",
    summonerTag: "TwilightEdge#NA1",
    role: "MID",
    region: "NA1",
    archetype: "ASSASSIN",
    basePrice: 176.3,
    volatility: 0.055,
    winRate: 59.7,
    leaguePoints: 1065,
    pviBase: 76,
    momentum: 0.0063,
    biography: "Shadows the map. If a carry shows, he's already flanking.",
    strengths: ["flank routes", "pick potential", "roam success rate"],
    weaknesses: ["losing matchups in lane", "follow-up dependent"],
  },
  {
    id: "syn-029",
    displayName: "UrgeWave",
    summonerTag: "UrgeWave#NA1",
    role: "ADC",
    region: "NA1",
    archetype: "HYPERCARRY",
    basePrice: 202.1,
    volatility: 0.059,
    winRate: 61.2,
    leaguePoints: 1199,
    pviBase: 83,
    momentum: 0.0085,
    biography: "Aggressive laner who snowballs leads faster than anyone.",
    strengths: ["laning aggression", "early game snowball", "lead pressing"],
    weaknesses: ["conceding leads", "passive playstyles"],
  },
  {
    id: "syn-030",
    displayName: "VexPoint",
    summonerTag: "VexPoint#NA1",
    role: "SUPPORT",
    region: "NA1",
    archetype: "SCALING_MAGE",
    basePrice: 94.0,
    volatility: 0.041,
    winRate: 52.3,
    leaguePoints: 565,
    pviBase: 55,
    momentum: -0.0017,
    biography: "Mage support who pokes enemies out of lane, then nukes them in teamfights.",
    strengths: ["poke damage", "teamfight burst", "AP itemization"],
    weaknesses: ["engage matchups", "missing skillshots at crit moments"],
  },
  {
    id: "syn-031",
    displayName: "WarpLine",
    summonerTag: "WarpLine#NA1",
    role: "TOP",
    region: "NA1",
    archetype: "WILDCARD",
    basePrice: 158.4,
    volatility: 0.071,
    winRate: 57.0,
    leaguePoints: 871,
    pviBase: 69,
    momentum: 0.0058,
    biography: "Experimental champion pool. Patches can make or break his season.",
    strengths: ["off-meta picks", "surprise factor", "adapting mid-game"],
    weaknesses: ["meta-dependent", "high variance outcomes"],
  },
  {
    id: "syn-032",
    displayName: "XenolithArc",
    summonerTag: "XenolithArc#NA1",
    role: "JUNGLE",
    region: "NA1",
    archetype: "HYPERCARRY",
    basePrice: 211.6,
    volatility: 0.064,
    winRate: 62.7,
    leaguePoints: 1420,
    pviBase: 87,
    momentum: 0.0112,
    biography: "Carry jungler who creates his own vision — never relies on laners to win.",
    strengths: ["farming efficiency", "side lane presence", "solo objective wins"],
    weaknesses: ["communication-dependent plays", "needs early advantages"],
  },
  {
    id: "syn-033",
    displayName: "YellowFang",
    summonerTag: "YellowFang#NA1",
    role: "MID",
    region: "NA1",
    archetype: "TEAMFIGHT_CARRY",
    basePrice: 167.9,
    volatility: 0.046,
    winRate: 59.1,
    leaguePoints: 1008,
    pviBase: 77,
    momentum: 0.0061,
    biography: "Teamfight powerhouse. The bigger the fight, the bigger the play.",
    strengths: ["AoE damage", "teamfight reads", "crowd control chains"],
    weaknesses: ["1v1 matchups", "isolated skirmishes"],
  },
  {
    id: "syn-034",
    displayName: "ZeroKelvin",
    summonerTag: "ZeroKelvin#NA1",
    role: "SUPPORT",
    region: "NA1",
    archetype: "ENGAGE_SUPPORT",
    basePrice: 131.2,
    volatility: 0.034,
    winRate: 56.4,
    leaguePoints: 834,
    pviBase: 71,
    momentum: 0.0037,
    biography: "Cold, calculated. Sets up every kill with robotic precision.",
    strengths: ["engage timing", "CC chains", "shotcalling"],
    weaknesses: ["improvisation", "falling behind in poke lanes"],
  },
  {
    id: "syn-035",
    displayName: "AbyssShade",
    summonerTag: "AbyssShade#NA1",
    role: "TOP",
    region: "NA1",
    archetype: "ASSASSIN",
    basePrice: 194.7,
    volatility: 0.058,
    winRate: 61.5,
    leaguePoints: 1247,
    pviBase: 83,
    momentum: 0.0097,
    biography: "Slippery as mercury. Escapes ganks that should be guaranteed kills.",
    strengths: ["escape mechanics", "split-push dominance", "1v2 handling"],
    weaknesses: ["teamfight coordination", "team reliance"],
  },
  {
    id: "syn-036",
    displayName: "BrightSpear",
    summonerTag: "BrightSpear#NA1",
    role: "JUNGLE",
    region: "NA1",
    archetype: "UTILITY_SUPPORT",
    basePrice: 107.8,
    volatility: 0.026,
    winRate: 54.9,
    leaguePoints: 712,
    pviBase: 64,
    momentum: 0.0014,
    biography: "Support jungler who enables laners to win their own lanes.",
    strengths: ["camp sharing", "laner setup", "protective jungling"],
    weaknesses: ["solo carry output", "resource efficiency"],
  },
  {
    id: "syn-037",
    displayName: "CobaltWing",
    summonerTag: "CobaltWing#NA1",
    role: "ADC",
    region: "NA1",
    archetype: "TEAMFIGHT_CARRY",
    basePrice: 184.3,
    volatility: 0.047,
    winRate: 60.8,
    leaguePoints: 1168,
    pviBase: 81,
    momentum: 0.0082,
    biography: "Built for teamfights — every fight he's in, the outcome shifts.",
    strengths: ["sustained DPS in fights", "positioning mastery", "self-peel"],
    weaknesses: ["2v2 bot lane aggression", "lane bully matchups"],
  },
  {
    id: "syn-038",
    displayName: "DeltaRise",
    summonerTag: "DeltaRise#NA1",
    role: "MID",
    region: "NA1",
    archetype: "SCALING_MAGE",
    basePrice: 145.6,
    volatility: 0.040,
    winRate: 57.4,
    leaguePoints: 888,
    pviBase: 72,
    momentum: 0.0043,
    biography: "Patient mid laner who outscales every opponent given time.",
    strengths: ["wave management", "power spike timing", "mage fundamentals"],
    weaknesses: ["early pressure trades", "fast-paced carry metas"],
  },
  {
    id: "syn-039",
    displayName: "EmberCrest",
    summonerTag: "EmberCrest#NA1",
    role: "TOP",
    region: "NA1",
    archetype: "TEAMFIGHT_CARRY",
    basePrice: 160.2,
    volatility: 0.044,
    winRate: 58.0,
    leaguePoints: 925,
    pviBase: 74,
    momentum: 0.0052,
    biography: "Transitional top laner. Farms early, takes over in mid-game teamfights.",
    strengths: ["flex picks", "TP fights", "tower priority"],
    weaknesses: ["early game pressure", "extended top lane camping"],
  },
  {
    id: "syn-040",
    displayName: "PhantomBurst",
    summonerTag: "PhantomBurst#NA1",
    role: "SUPPORT",
    region: "NA1",
    archetype: "ASSASSIN",
    basePrice: 136.9,
    volatility: 0.052,
    winRate: 55.7,
    leaguePoints: 808,
    pviBase: 69,
    momentum: 0.0030,
    biography: "Assassin support — you don't see him until your carry is dead.",
    strengths: ["backline access", "surprising burst", "roam kill potential"],
    weaknesses: ["peel", "safe playstyle ADCs"],
  },
];
